### ISSUE TITLE
Corretto Patch Possibilities, IEEE 754 oversight, the nature of Patches, Logic Errors.

### ISSUE THREAD

**Issue by PowerUser1234** [corretto/corretto-18#23] opened 2022-04-21 06:48 UTC
Dear Corretto,

from what we have gathered, both ourselves and more widely, IEEE 754 has a blind spot in it. An incompletion where either right or wrong can creep in. This is towards the right hand side of float or double arithmetic and StrictMath method calls,
where you have a straddling value for the last decimal place, that at that point is a confusion between the decimal and the binary; the decimal, which the human sees, and the binary, which is converterted to and away from, that the computer needs to perform operations on.

Since binary is for computers, and decimal is for humans, the most important root fact anyway, dealing with both of them means that you should deal with them one at a time, or convert them, entirely, one to the other. This is exactly what Java floating point does not do. It deliberately confuses the two, at the wrong time, with denormals and pronormals, leading to what should be seen as 'floating point errors'.

The thing with a patch is that it is not the main stream, the primary product. People have the specific option to include one or not. Who could want or need a denormal or pronormal value, exactedly? Any speed difference between accurate or innacurate is negligible because of SSE and similar anyway. Why should all ubiquity Java Developers have no broader choice about how they react about an incomplete, therefore incorrect and flawed standard, and implementation? Present workarounds are only that, workarounds, and with float and double range are slower and larger than needs be. A patch can leave the writing or reading or exchange of float and double between Java code spaces exactly the same, providing complete choice between two Java floating point operation modes.

Most importantly, what should happen about floating point error correction should Oracle, OpenJDK, JCP et al, the ideal points for improvement on FP errors, never listen, and persist in leaving these errors and program operations problem intact? Surely it would be better for a downstream vendor to offer a patch for the problem, which is lower risk and apart from the mainstream, than this error problem remain ongoing and neglected in place, forever.

When the Java switch statement was enhanced, so that programmers could immediately switch via a String, and could also coelesce switch options using the -> operator, there was no split in Java because of an incompatability. The fact that people had cause to learn something different and new about switch was no problem either. The two compatability options only
improved the circumstances for everyone.

If these are the needs and the circumstances, should Corretto at least consider a special Floating Point patch for Corretto Java, despites?

**Comment by alvdavi** [comment] 2022-04-21 21:10
Closing as duplicate of #18, which is also duplicated with #17, #16 and #15. Please, let's keep the conversation in one single issue, as opening duplicates will only make following the different messages harder.

**Closed as completed by alvdavi** 2022-04-21 21:10 UTC

**Comment by PowerUser1234** [comment] 2022-04-22 06:12
If I continue to post or reply to an issue which has been closed, will it continue to send an email or raise a flag or active attention with the people who check the Corretto Java Issues area?

At any rate, whether the points I have raised are repetitions or not (I have tried to make them specific replies to responses from the Corretto side of the exchange), they are all true points and don't deserve to be ignored or blithely dismissed, certainly by just one person (either).

**********************************************************************************************************************************
In terms of the nature of a patch, differing away from the main object of the software artifact, concerns about compatability or risk or differing from the mainstream can be easily dismissed (look at what happened when the switch statement changed).  Corretto stands to make real gains for itself by implementing a floating point correction patch.

If indeed Oracle won't respond or begin to listen, that pretty well locks floating point correction out of SE and OpenJDK for the rest of us, and the all of us.  The only ubiquity option is if another OpenJDK related vendor were prepared to do this differently.
If not, the root of the Java floating point error will remain the logic error that it is, addressed only by a stop gap measure, which is a hack with a set of object disadvantages, reducing the quality, speed and efficiency of Java maybe forever.

**********************************************************************************************************************************
