### ISSUE TITLE
Java Error Repairs.

### ISSUE THREAD

**Issue by PowerUser1234** [corretto/corretto-18#26] opened 2022-04-27 04:43 UTC
-If I/we were to change the OpenJDK and republish it, it will not enter into ubiquity, certainly not in the same way.  Other Java programmers are all entitled to improved floating point, as are any other professional entities.  They are also entitled to increased credibility from the origin of the corrections, certainly given the the origin of the problem.

-We indeed do think that Java is the right language for us.  However, people involved don't have the additional knowledge
or skill to implement the changes necessary in C and assembly, and bindings involved, (certainly not for every platform and relese version number to come). They are not particularly able to, nor should they have to be so.  
This is due to the point following:

-OpenJDK, with JCP, is supposed to be a community, and in a community, people are allowed to rely on others in that community.  The state of Java OpenJDK floating point is within the state of a computer error, a bug. It has to be changed, and aught be, by whoever is producing the implementation code involved, as is true of any computer program and software developer.  The problem is that the original developers are not showing to be ameniable to both the necessity involved and the action required.

-Leaving the only improved alternative, other official Java Vendors.

-IEEE 754 is incomplete, and states nothing about denormal and pronormal value errors from float and double.  IEEE 754
is already not entirely seized from anyway.  Therefore if not for the original vendor, other official vendors may have to consider
doing something else better in this regard.

-The BigInteger, BigDecimal, big-math workarounds are only that, stop-gap measures, which are not correct options.  They are too slow, too large in memory, and more complicated to deal with than necessary, certainly within range of of float or double.  They are not
an alternative, but a flawed and temporary state of affairs, awaiting better implementation.

-Default change is only one option, since there can be dual mode, compatible change too.  This can still be wrought without
changing how the language compiles, if desired.  What could even be more compatible again is if a separate patch were developed,
which can be installed, or not.  This is the reason why Corretto is now in an elevated and ideal position to debug these language
errors.

Can Corretto Java please do something in regards to these software errors, where others can't and won't?

**Comment by alvdavi** [comment] 2022-04-27 04:55
Closing as duplicate of #18, which is also duplicated with #15, #16, #17, #23 and #25. This request has already received an answer by the team

**Closed as completed by alvdavi** 2022-04-27 04:55 UTC
Labels: wontfix
